### ISSUE TITLE
[Feature] Pass node properties to form

### ISSUE THREAD

**Issue by ghost** [neos/form#44]
It would be great, if you could pass data e.g. from your site node to the form and include them in a e.g. in a hidden form element. 

**Example use case**
_Registration_
Passing details of an event so that you can use the form to register and predefine information e.g. event name, date, ... which will also be available in the finisher

**Comment by bwaidelich** [comment]
This is already possible with the `overrideConfiguration` Setting.
e.g. when having a form definition like this:
```yaml
type: 'Neos.Form:Form'
identifier: some-form
renderables:
    -
        type: 'Neos.Form:Page'
        identifier: page1
        label: 'Page 1'
        renderables:
            -
                type: 'Neos.Form:HiddenField'
                identifier: 'node'
                label: 'hidden'
```

That `node` hidden field value can be set via Fusion like that
```fusion
prototype(Some.Custom:Form) < prototype(Neos.NodeTypes:Form) {
	overrideConfiguration = Neos.Fusion:RawArray {
		renderables = Neos.Fusion:RawArray {
			# first page
			0 = Neos.Fusion:RawArray {
				renderables = Neos.Fusion:RawArray {
					# first renderable
					0 = Neos.Fusion:RawArray {
						defaultValue = ${node.identifier}
					}
				}
			}
		}
	}
}
```

Frankly, that Fusion is a bit convoluted, but a custom helper/implementation could be used to make this easier to use.
**Note:** hidden field values are not protected and could be changed by the client. To prevent that, a custom Form Element could be defined
